// Code generated by counterfeiter. DO NOT EDIT.
package transferfakes

import (
	"sync"

	"github.com/cheggaaa/pb"
	"github.com/dpb587/metalink"
	"github.com/dpb587/metalink/file"
	"github.com/dpb587/metalink/transfer"
	"github.com/dpb587/metalink/verification"
)

type FakeTransfer struct {
	TransferFileStub        func(metalink.File, file.Reference, *pb.ProgressBar, verification.VerificationResultReporter) error
	transferFileMutex       sync.RWMutex
	transferFileArgsForCall []struct {
		arg1 metalink.File
		arg2 file.Reference
		arg3 *pb.ProgressBar
		arg4 verification.VerificationResultReporter
	}
	transferFileReturns struct {
		result1 error
	}
	transferFileReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTransfer) TransferFile(arg1 metalink.File, arg2 file.Reference, arg3 *pb.ProgressBar, arg4 verification.VerificationResultReporter) error {
	fake.transferFileMutex.Lock()
	ret, specificReturn := fake.transferFileReturnsOnCall[len(fake.transferFileArgsForCall)]
	fake.transferFileArgsForCall = append(fake.transferFileArgsForCall, struct {
		arg1 metalink.File
		arg2 file.Reference
		arg3 *pb.ProgressBar
		arg4 verification.VerificationResultReporter
	}{arg1, arg2, arg3, arg4})
	stub := fake.TransferFileStub
	fakeReturns := fake.transferFileReturns
	fake.recordInvocation("TransferFile", []interface{}{arg1, arg2, arg3, arg4})
	fake.transferFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTransfer) TransferFileCallCount() int {
	fake.transferFileMutex.RLock()
	defer fake.transferFileMutex.RUnlock()
	return len(fake.transferFileArgsForCall)
}

func (fake *FakeTransfer) TransferFileCalls(stub func(metalink.File, file.Reference, *pb.ProgressBar, verification.VerificationResultReporter) error) {
	fake.transferFileMutex.Lock()
	defer fake.transferFileMutex.Unlock()
	fake.TransferFileStub = stub
}

func (fake *FakeTransfer) TransferFileArgsForCall(i int) (metalink.File, file.Reference, *pb.ProgressBar, verification.VerificationResultReporter) {
	fake.transferFileMutex.RLock()
	defer fake.transferFileMutex.RUnlock()
	argsForCall := fake.transferFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeTransfer) TransferFileReturns(result1 error) {
	fake.transferFileMutex.Lock()
	defer fake.transferFileMutex.Unlock()
	fake.TransferFileStub = nil
	fake.transferFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTransfer) TransferFileReturnsOnCall(i int, result1 error) {
	fake.transferFileMutex.Lock()
	defer fake.transferFileMutex.Unlock()
	fake.TransferFileStub = nil
	if fake.transferFileReturnsOnCall == nil {
		fake.transferFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.transferFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTransfer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.transferFileMutex.RLock()
	defer fake.transferFileMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTransfer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ transfer.Transfer = new(FakeTransfer)
