// Code generated by counterfeiter. DO NOT EDIT.
package verificationfakes

import (
	"sync"

	"github.com/dpb587/metalink"
	"github.com/dpb587/metalink/file"
	"github.com/dpb587/metalink/verification"
)

type FakeSignerVerifier struct {
	SignStub        func(file.Reference) (verification.Verification, error)
	signMutex       sync.RWMutex
	signArgsForCall []struct {
		arg1 file.Reference
	}
	signReturns struct {
		result1 verification.Verification
		result2 error
	}
	signReturnsOnCall map[int]struct {
		result1 verification.Verification
		result2 error
	}
	VerifyStub        func(file.Reference, metalink.File) verification.VerificationResult
	verifyMutex       sync.RWMutex
	verifyArgsForCall []struct {
		arg1 file.Reference
		arg2 metalink.File
	}
	verifyReturns struct {
		result1 verification.VerificationResult
	}
	verifyReturnsOnCall map[int]struct {
		result1 verification.VerificationResult
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSignerVerifier) Sign(arg1 file.Reference) (verification.Verification, error) {
	fake.signMutex.Lock()
	ret, specificReturn := fake.signReturnsOnCall[len(fake.signArgsForCall)]
	fake.signArgsForCall = append(fake.signArgsForCall, struct {
		arg1 file.Reference
	}{arg1})
	stub := fake.SignStub
	fakeReturns := fake.signReturns
	fake.recordInvocation("Sign", []interface{}{arg1})
	fake.signMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSignerVerifier) SignCallCount() int {
	fake.signMutex.RLock()
	defer fake.signMutex.RUnlock()
	return len(fake.signArgsForCall)
}

func (fake *FakeSignerVerifier) SignCalls(stub func(file.Reference) (verification.Verification, error)) {
	fake.signMutex.Lock()
	defer fake.signMutex.Unlock()
	fake.SignStub = stub
}

func (fake *FakeSignerVerifier) SignArgsForCall(i int) file.Reference {
	fake.signMutex.RLock()
	defer fake.signMutex.RUnlock()
	argsForCall := fake.signArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSignerVerifier) SignReturns(result1 verification.Verification, result2 error) {
	fake.signMutex.Lock()
	defer fake.signMutex.Unlock()
	fake.SignStub = nil
	fake.signReturns = struct {
		result1 verification.Verification
		result2 error
	}{result1, result2}
}

func (fake *FakeSignerVerifier) SignReturnsOnCall(i int, result1 verification.Verification, result2 error) {
	fake.signMutex.Lock()
	defer fake.signMutex.Unlock()
	fake.SignStub = nil
	if fake.signReturnsOnCall == nil {
		fake.signReturnsOnCall = make(map[int]struct {
			result1 verification.Verification
			result2 error
		})
	}
	fake.signReturnsOnCall[i] = struct {
		result1 verification.Verification
		result2 error
	}{result1, result2}
}

func (fake *FakeSignerVerifier) Verify(arg1 file.Reference, arg2 metalink.File) verification.VerificationResult {
	fake.verifyMutex.Lock()
	ret, specificReturn := fake.verifyReturnsOnCall[len(fake.verifyArgsForCall)]
	fake.verifyArgsForCall = append(fake.verifyArgsForCall, struct {
		arg1 file.Reference
		arg2 metalink.File
	}{arg1, arg2})
	stub := fake.VerifyStub
	fakeReturns := fake.verifyReturns
	fake.recordInvocation("Verify", []interface{}{arg1, arg2})
	fake.verifyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSignerVerifier) VerifyCallCount() int {
	fake.verifyMutex.RLock()
	defer fake.verifyMutex.RUnlock()
	return len(fake.verifyArgsForCall)
}

func (fake *FakeSignerVerifier) VerifyCalls(stub func(file.Reference, metalink.File) verification.VerificationResult) {
	fake.verifyMutex.Lock()
	defer fake.verifyMutex.Unlock()
	fake.VerifyStub = stub
}

func (fake *FakeSignerVerifier) VerifyArgsForCall(i int) (file.Reference, metalink.File) {
	fake.verifyMutex.RLock()
	defer fake.verifyMutex.RUnlock()
	argsForCall := fake.verifyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSignerVerifier) VerifyReturns(result1 verification.VerificationResult) {
	fake.verifyMutex.Lock()
	defer fake.verifyMutex.Unlock()
	fake.VerifyStub = nil
	fake.verifyReturns = struct {
		result1 verification.VerificationResult
	}{result1}
}

func (fake *FakeSignerVerifier) VerifyReturnsOnCall(i int, result1 verification.VerificationResult) {
	fake.verifyMutex.Lock()
	defer fake.verifyMutex.Unlock()
	fake.VerifyStub = nil
	if fake.verifyReturnsOnCall == nil {
		fake.verifyReturnsOnCall = make(map[int]struct {
			result1 verification.VerificationResult
		})
	}
	fake.verifyReturnsOnCall[i] = struct {
		result1 verification.VerificationResult
	}{result1}
}

func (fake *FakeSignerVerifier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.signMutex.RLock()
	defer fake.signMutex.RUnlock()
	fake.verifyMutex.RLock()
	defer fake.verifyMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSignerVerifier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ verification.SignerVerifier = new(FakeSignerVerifier)
