// This file was generated by counterfeiter
package verificationfakes

import (
	"sync"

	"github.com/dpb587/metalink"
	"github.com/dpb587/metalink/file"
	"github.com/dpb587/metalink/verification"
)

type FakeVerification struct {
	SignStub        func(file.Reference) (verification.Result, error)
	signMutex       sync.RWMutex
	signArgsForCall []struct {
		arg1 file.Reference
	}
	signReturns struct {
		result1 verification.Result
		result2 error
	}
	VerifyStub        func(file.Reference, metalink.File) error
	verifyMutex       sync.RWMutex
	verifyArgsForCall []struct {
		arg1 file.Reference
		arg2 metalink.File
	}
	verifyReturns struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVerification) Sign(arg1 file.Reference) (verification.Result, error) {
	fake.signMutex.Lock()
	fake.signArgsForCall = append(fake.signArgsForCall, struct {
		arg1 file.Reference
	}{arg1})
	fake.recordInvocation("Sign", []interface{}{arg1})
	fake.signMutex.Unlock()
	if fake.SignStub != nil {
		return fake.SignStub(arg1)
	}
	return fake.signReturns.result1, fake.signReturns.result2
}

func (fake *FakeVerification) SignCallCount() int {
	fake.signMutex.RLock()
	defer fake.signMutex.RUnlock()
	return len(fake.signArgsForCall)
}

func (fake *FakeVerification) SignArgsForCall(i int) file.Reference {
	fake.signMutex.RLock()
	defer fake.signMutex.RUnlock()
	return fake.signArgsForCall[i].arg1
}

func (fake *FakeVerification) SignReturns(result1 verification.Result, result2 error) {
	fake.SignStub = nil
	fake.signReturns = struct {
		result1 verification.Result
		result2 error
	}{result1, result2}
}

func (fake *FakeVerification) Verify(arg1 file.Reference, arg2 metalink.File) error {
	fake.verifyMutex.Lock()
	fake.verifyArgsForCall = append(fake.verifyArgsForCall, struct {
		arg1 file.Reference
		arg2 metalink.File
	}{arg1, arg2})
	fake.recordInvocation("Verify", []interface{}{arg1, arg2})
	fake.verifyMutex.Unlock()
	if fake.VerifyStub != nil {
		return fake.VerifyStub(arg1, arg2)
	}
	return fake.verifyReturns.result1
}

func (fake *FakeVerification) VerifyCallCount() int {
	fake.verifyMutex.RLock()
	defer fake.verifyMutex.RUnlock()
	return len(fake.verifyArgsForCall)
}

func (fake *FakeVerification) VerifyArgsForCall(i int) (file.Reference, metalink.File) {
	fake.verifyMutex.RLock()
	defer fake.verifyMutex.RUnlock()
	return fake.verifyArgsForCall[i].arg1, fake.verifyArgsForCall[i].arg2
}

func (fake *FakeVerification) VerifyReturns(result1 error) {
	fake.VerifyStub = nil
	fake.verifyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVerification) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.signMutex.RLock()
	defer fake.signMutex.RUnlock()
	fake.verifyMutex.RLock()
	defer fake.verifyMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeVerification) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ verification.Verification = new(FakeVerification)
