name: exports-upload-github-release
inputs:
  repository_path:
    default: repository
  release:
    default: ${{ github.ref_name }}
  is_latest_release:
    default: "true"
outputs:
  is_latest_release:
    value: ${{ steps.assertions.outputs.is_latest_release }}
runs:
  using: "composite"
  steps:
    - id: assertions
      name: assertions
      shell: bash
      run: |
        # assertions

        cd "${{ inputs.repository_path }}"

        if ! git ls-remote --tags origin '${{ github.ref_name }}^{}'
        then
          echo tag is not annotated >&2
          exit 1
        elif ! git merge-base --is-ancestor $( git rev-parse HEAD ) refs/remotes/origin/main
        then
          echo tag diveraged from main >&2
          exit 1
        fi

        if [[ "${{ github.ref_name }}" == "$( git tag -l --sort=-version:refname | head -n1 )" ]]
        then
          echo "is_latest_release=true" >> "${GITHUB_OUTPUT}"
        else
          echo "is_latest_release=false" >> "${GITHUB_OUTPUT}"
        fi
    - name: create-release
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        # create-release

        cd "${{ inputs.repository_path }}"

        gh release create "${{ github.ref_name }}" \
          --draft \
          --prerelease=${{ toJSON(contains(github.ref_name, '-')) }} \
          --title "${{ github.ref_name }}"
