// This file was generated by counterfeiter
package urlfakes

import (
	"sync"

	"github.com/dpb587/metalink"
	"github.com/dpb587/metalink/file"
	"github.com/dpb587/metalink/file/url"
)

type FakeLoader struct {
	LoadStub        func(metalink.URL) (file.Reference, error)
	loadMutex       sync.RWMutex
	loadArgsForCall []struct {
		arg1 metalink.URL
	}
	loadReturns struct {
		result1 file.Reference
		result2 error
	}
	SchemesStub        func() []string
	schemesMutex       sync.RWMutex
	schemesArgsForCall []struct{}
	schemesReturns     struct {
		result1 []string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeLoader) Load(arg1 metalink.URL) (file.Reference, error) {
	fake.loadMutex.Lock()
	fake.loadArgsForCall = append(fake.loadArgsForCall, struct {
		arg1 metalink.URL
	}{arg1})
	fake.recordInvocation("Load", []interface{}{arg1})
	fake.loadMutex.Unlock()
	if fake.LoadStub != nil {
		return fake.LoadStub(arg1)
	}
	return fake.loadReturns.result1, fake.loadReturns.result2
}

func (fake *FakeLoader) LoadCallCount() int {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	return len(fake.loadArgsForCall)
}

func (fake *FakeLoader) LoadArgsForCall(i int) metalink.URL {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	return fake.loadArgsForCall[i].arg1
}

func (fake *FakeLoader) LoadReturns(result1 file.Reference, result2 error) {
	fake.LoadStub = nil
	fake.loadReturns = struct {
		result1 file.Reference
		result2 error
	}{result1, result2}
}

func (fake *FakeLoader) Schemes() []string {
	fake.schemesMutex.Lock()
	fake.schemesArgsForCall = append(fake.schemesArgsForCall, struct{}{})
	fake.recordInvocation("Schemes", []interface{}{})
	fake.schemesMutex.Unlock()
	if fake.SchemesStub != nil {
		return fake.SchemesStub()
	}
	return fake.schemesReturns.result1
}

func (fake *FakeLoader) SchemesCallCount() int {
	fake.schemesMutex.RLock()
	defer fake.schemesMutex.RUnlock()
	return len(fake.schemesArgsForCall)
}

func (fake *FakeLoader) SchemesReturns(result1 []string) {
	fake.SchemesStub = nil
	fake.schemesReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeLoader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	fake.schemesMutex.RLock()
	defer fake.schemesMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeLoader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ url.Loader = new(FakeLoader)
